import { getDb } from "./index";
import { marketAssets, sectors, earningsReports, supportTickets, userWatchlist, marketAlerts } from "./schema";

export async function seedDatabase() {
  const db = await getDb();
  // Check if assets already exist
  const existingAssets = await db.select().from(marketAssets).limit(1);
  if (existingAssets.length > 0) {
    return;
  }

  // 1. Seed Market Assets
  await db.insert(marketAssets).values([
    // Major Global Indices
    {
      symbol: "SPX",
      name: "S&P 500 Index",
      category: "equities",
      price: "5910.45",
      change: "36.40",
      changePercent: "0.62",
      high24h: "5925.10",
      low24h: "5884.20",
      volume: "$48.2B",
      marketCap: "$47.8T",
      peRatio: "26.40",
      dividendYield: "1.32",
      sparkline: [5840, 5865, 5850, 5890, 5880, 5905, 5910.45],
      aiSentiment: "Bullish",
      aiSummary: "Broad-based breadth expansion supported by robust tech capex and softening disinflation expectations.",
      exchange: "NYSE / CBOE",
    },
    {
      symbol: "NDX",
      name: "Nasdaq 100",
      category: "equities",
      price: "20845.20",
      change: "182.10",
      changePercent: "0.88",
      high24h: "20910.00",
      low24h: "20712.50",
      volume: "$36.5B",
      marketCap: "$22.4T",
      peRatio: "31.20",
      dividendYield: "0.85",
      sparkline: [20450, 20520, 20680, 20610, 20750, 20810, 20845.2],
      aiSentiment: "Bullish",
      aiSummary: "Mega-cap cloud & AI infrastructure leaders pacing record-high free cash flow yields.",
      exchange: "NASDAQ",
    },
    {
      symbol: "DJI",
      name: "Dow Jones Industrial Average",
      category: "equities",
      price: "43870.15",
      change: "154.30",
      changePercent: "0.35",
      high24h: "43950.00",
      low24h: "43720.00",
      volume: "$16.8B",
      marketCap: "$13.9T",
      peRatio: "22.80",
      dividendYield: "1.82",
      sparkline: [43400, 43550, 43620, 43580, 43750, 43810, 43870.15],
      aiSentiment: "Neutral",
      aiSummary: "Financials and industrials maintaining steady dividend coverage despite cyclical manufacturing headwinds.",
      exchange: "NYSE",
    },
    {
      symbol: "FTSE",
      name: "FTSE 100 (UK)",
      category: "equities",
      price: "8425.60",
      change: "34.50",
      changePercent: "0.41",
      high24h: "8445.00",
      low24h: "8390.20",
      volume: "£9.1B",
      marketCap: "£2.4T",
      peRatio: "14.20",
      dividendYield: "3.75",
      sparkline: [8360, 8390, 8380, 8410, 8405, 8415, 8425.6],
      aiSentiment: "Neutral",
      aiSummary: "Commodity exporters and aerospace firms insulating London benchmarks from domestic fiscal belt-tightening.",
      exchange: "LSE",
    },
    {
      symbol: "N225",
      name: "Nikkei 225 (Japan)",
      category: "equities",
      price: "39280.00",
      change: "445.00",
      changePercent: "1.15",
      high24h: "39420.00",
      low24h: "38950.00",
      volume: "¥3.8T",
      marketCap: "¥680T",
      peRatio: "16.80",
      dividendYield: "1.95",
      sparkline: [38400, 38650, 38800, 38720, 39050, 39180, 39280],
      aiSentiment: "Bullish",
      aiSummary: "Tokyo Stock Exchange governance reforms and sustained foreign institutional buying driving breakout momentum.",
      exchange: "TSE",
    },
    {
      symbol: "DAX",
      name: "DAX 40 (Germany)",
      category: "equities",
      price: "19450.30",
      change: "106.20",
      changePercent: "0.55",
      high24h: "19510.00",
      low24h: "19380.00",
      volume: "€5.4B",
      marketCap: "€1.9T",
      peRatio: "15.10",
      dividendYield: "2.90",
      sparkline: [19200, 19280, 19340, 19300, 19410, 19420, 19450.3],
      aiSentiment: "Neutral",
      aiSummary: "Export heavyweight resilience in software and medical technology offsetting chemical sector sluggishness.",
      exchange: "Deutsche Börse",
    },
    {
      symbol: "HSI",
      name: "Hang Seng (Hong Kong)",
      category: "equities",
      price: "20620.10",
      change: "-51.80",
      changePercent: "-0.25",
      high24h: "20780.00",
      low24h: "20540.00",
      volume: "HK$112B",
      marketCap: "HK$34T",
      peRatio: "10.40",
      dividendYield: "3.80",
      sparkline: [20900, 20810, 20750, 20820, 20690, 20650, 20620.1],
      aiSentiment: "Cautious",
      aiSummary: "Market awaiting clear follow-through details on domestic consumer liquidity incentives.",
      exchange: "HKEX",
    },
    {
      symbol: "NIFTY",
      name: "Nifty 50 (India)",
      category: "equities",
      price: "24180.50",
      change: "172.90",
      changePercent: "0.72",
      high24h: "24250.00",
      low24h: "24040.00",
      volume: "₹620B",
      marketCap: "₹185T",
      peRatio: "22.50",
      dividendYield: "1.18",
      sparkline: [23850, 23940, 24010, 23980, 24110, 24150, 24180.5],
      aiSentiment: "Bullish",
      aiSummary: "Unabated domestic SIP mutual fund inflows powering capital goods and banking credit expansion.",
      exchange: "NSE",
    },

    // Tech & AI Leaders
    {
      symbol: "NVDA",
      name: "NVIDIA Corporation",
      category: "tech-ai",
      price: "138.25",
      change: "4.18",
      changePercent: "3.12",
      high24h: "139.80",
      low24h: "134.60",
      volume: "$24.1B",
      marketCap: "$3.38T",
      peRatio: "48.20",
      dividendYield: "0.03",
      sparkline: [131, 133, 132.5, 135, 134.2, 136.8, 138.25],
      aiSentiment: "Strong Bullish",
      aiSummary: "Blackwell ultra-scale cluster deployments booked out 12+ months across Tier-1 hyperscalers.",
      exchange: "NASDAQ",
    },
    {
      symbol: "AAPL",
      name: "Apple Inc.",
      category: "tech-ai",
      price: "232.80",
      change: "2.42",
      changePercent: "1.05",
      high24h: "234.10",
      low24h: "230.90",
      volume: "$11.2B",
      marketCap: "$3.52T",
      peRatio: "34.10",
      dividendYield: "0.43",
      sparkline: [228, 229.5, 231, 230.2, 231.8, 232.1, 232.8],
      aiSentiment: "Bullish",
      aiSummary: "Services ecosystem revenue run-rate approaching $100B with 74% gross margins.",
      exchange: "NASDAQ",
    },
    {
      symbol: "MSFT",
      name: "Microsoft Corporation",
      category: "tech-ai",
      price: "428.50",
      change: "5.90",
      changePercent: "1.40",
      high24h: "431.20",
      low24h: "424.00",
      volume: "$9.8B",
      marketCap: "$3.18T",
      peRatio: "33.60",
      dividendYield: "0.78",
      sparkline: [419, 421, 423, 422.5, 425, 426.8, 428.5],
      aiSentiment: "Bullish",
      aiSummary: "Azure commercial cloud consumption growing 33% YoY with Copilot enterprise penetration accelerating.",
      exchange: "NASDAQ",
    },
    {
      symbol: "GOOGL",
      name: "Alphabet Inc.",
      category: "tech-ai",
      price: "178.60",
      change: "2.12",
      changePercent: "1.20",
      high24h: "180.20",
      low24h: "176.80",
      volume: "$6.4B",
      marketCap: "$2.21T",
      peRatio: "22.80",
      dividendYield: "0.45",
      sparkline: [173, 174.5, 176, 175.2, 177, 177.8, 178.6],
      aiSentiment: "Bullish",
      aiSummary: "YouTube ad revenue and Google Cloud operating margin inflection to 11.7% confirming pricing power.",
      exchange: "NASDAQ",
    },
    {
      symbol: "TSLA",
      name: "Tesla Inc.",
      category: "tech-ai",
      price: "318.90",
      change: "14.60",
      changePercent: "4.80",
      high24h: "324.50",
      low24h: "306.20",
      volume: "$18.5B",
      marketCap: "$1.02T",
      peRatio: "88.40",
      dividendYield: "0.00",
      sparkline: [292, 298, 305, 301, 310, 314, 318.9],
      aiSentiment: "High Volatility",
      aiSummary: "Robotaxi fleet validation tests and Megapack energy storage delivery ramp up 125% YoY.",
      exchange: "NASDAQ",
    },

    // Macro & Commodities
    {
      symbol: "GOLD",
      name: "Spot Gold (XAU/USD)",
      category: "macro-commodities",
      price: "2685.40",
      change: "12.80",
      changePercent: "0.48",
      high24h: "2694.00",
      low24h: "2671.50",
      volume: "$38.6B",
      marketCap: "$17.4T",
      peRatio: null,
      dividendYield: null,
      sparkline: [2650, 2662, 2658, 2674, 2670, 2680, 2685.4],
      aiSentiment: "Bullish",
      aiSummary: "Sovereign reserve de-dollarization and relentless Asian central bank accumulation underpinning spot prices.",
      exchange: "COMEX / LBMA",
    },
    {
      symbol: "BRENT",
      name: "Brent Crude Oil",
      category: "macro-commodities",
      price: "74.20",
      change: "-0.48",
      changePercent: "-0.65",
      high24h: "75.10",
      low24h: "73.80",
      volume: "$22.4B",
      marketCap: null,
      peRatio: null,
      dividendYield: null,
      sparkline: [76.5, 75.8, 75.2, 74.9, 74.5, 74.8, 74.2],
      aiSentiment: "Neutral",
      aiSummary: "Non-OPEC+ supply gains offset by Middle East tanker route risk premia.",
      exchange: "ICE",
    },
    {
      symbol: "NATGAS",
      name: "Natural Gas (Henry Hub)",
      category: "macro-commodities",
      price: "2.88",
      change: "0.06",
      changePercent: "2.10",
      high24h: "2.94",
      low24h: "2.80",
      volume: "$4.1B",
      marketCap: null,
      peRatio: null,
      dividendYield: null,
      sparkline: [2.71, 2.75, 2.73, 2.81, 2.84, 2.86, 2.88],
      aiSentiment: "Bullish",
      aiSummary: "LNG export terminal expansions on US Gulf Coast driving steady withdrawal trajectories.",
      exchange: "NYMEX",
    },
    {
      symbol: "COPPER",
      name: "High Grade Copper",
      category: "macro-commodities",
      price: "4.22",
      change: "0.05",
      changePercent: "1.15",
      high24h: "4.26",
      low24h: "4.16",
      volume: "$6.8B",
      marketCap: null,
      peRatio: null,
      dividendYield: null,
      sparkline: [4.12, 4.15, 4.14, 4.19, 4.20, 4.21, 4.22],
      aiSentiment: "Bullish",
      aiSummary: "Global grid electrification and AI data center substation copper intensity creating structural deficit.",
      exchange: "COMEX",
    },

    // Crypto Assets
    {
      symbol: "BTC",
      name: "Bitcoin",
      category: "crypto",
      price: "94820.00",
      change: "2625.00",
      changePercent: "2.85",
      high24h: "95450.00",
      low24h: "92180.00",
      volume: "$42.8B",
      marketCap: "$1.87T",
      peRatio: null,
      dividendYield: null,
      sparkline: [90800, 91500, 92900, 92400, 93800, 94200, 94820],
      aiSentiment: "Strong Bullish",
      aiSummary: "Institutional spot ETF cumulative inflows topping $34B with corporate balance sheet adoptions escalating.",
      exchange: "Spot Aggregated",
    },
    {
      symbol: "ETH",
      name: "Ethereum",
      category: "crypto",
      price: "3420.50",
      change: "102.80",
      changePercent: "3.10",
      high24h: "3480.00",
      low24h: "3310.00",
      volume: "$18.6B",
      marketCap: "$411B",
      peRatio: null,
      dividendYield: null,
      sparkline: [3240, 3280, 3320, 3300, 3360, 3390, 3420.5],
      aiSentiment: "Bullish",
      aiSummary: "Layer 2 blob settlement gas burn accelerating and decentralized finance total value locked exceeding $68B.",
      exchange: "Spot Aggregated",
    },
    {
      symbol: "SOL",
      name: "Solana",
      category: "crypto",
      price: "218.40",
      change: "9.70",
      changePercent: "4.65",
      high24h: "224.10",
      low24h: "207.50",
      volume: "$8.9B",
      marketCap: "$103B",
      peRatio: null,
      dividendYield: null,
      sparkline: [198, 203, 209, 206, 212, 215, 218.4],
      aiSentiment: "Strong Bullish",
      aiSummary: "Record daily active addresses and decentralized exchange trading volumes rivaling centralized venues.",
      exchange: "Spot Aggregated",
    },

    // Forex & Currencies
    {
      symbol: "EURUSD",
      name: "EUR / USD",
      category: "forex",
      price: "1.0520",
      change: "-0.0016",
      changePercent: "-0.15",
      high24h: "1.0565",
      low24h: "1.0498",
      volume: "$142B",
      marketCap: null,
      peRatio: null,
      dividendYield: null,
      sparkline: [1.058, 1.056, 1.054, 1.055, 1.053, 1.0525, 1.052],
      aiSentiment: "Neutral",
      aiSummary: "Interest rate divergence between European Central Bank rate cuts and resilient US labor market data.",
      exchange: "Interbank FX",
    },
    {
      symbol: "USDJPY",
      name: "USD / JPY",
      category: "forex",
      price: "153.85",
      change: "0.46",
      changePercent: "0.30",
      high24h: "154.20",
      low24h: "153.10",
      volume: "$98B",
      marketCap: null,
      peRatio: null,
      dividendYield: null,
      sparkline: [152.8, 153.1, 153.5, 153.2, 153.6, 153.7, 153.85],
      aiSentiment: "Caution Intervention",
      aiSummary: "Bank of Japan rate hike timeline monitored closely; ministry verbal warnings limiting upside past 155.00.",
      exchange: "Interbank FX",
    },
    {
      symbol: "GBPUSD",
      name: "GBP / USD",
      category: "forex",
      price: "1.2640",
      change: "0.0015",
      changePercent: "0.12",
      high24h: "1.2680",
      low24h: "1.2610",
      volume: "$64B",
      marketCap: null,
      peRatio: null,
      dividendYield: null,
      sparkline: [1.259, 1.261, 1.263, 1.262, 1.265, 1.2635, 1.264],
      aiSentiment: "Neutral",
      aiSummary: "Sticky UK services inflation preventing Bank of England from aggressive easing cycles.",
      exchange: "Interbank FX",
    },

    // Fixed Income & Yields
    {
      symbol: "US10Y",
      name: "US 10-Year Treasury Yield",
      category: "bonds",
      price: "4.382",
      change: "-0.024",
      changePercent: "-0.54",
      high24h: "4.425",
      low24h: "4.360",
      volume: "$72B",
      marketCap: null,
      peRatio: null,
      dividendYield: "4.38",
      sparkline: [4.45, 4.43, 4.41, 4.40, 4.39, 4.385, 4.382],
      aiSentiment: "Consolidation",
      aiSummary: "Treasury auction demand remains solid; curve steepening expected as short-term policy rates ease.",
      exchange: "Govt Bond Desk",
    },
    {
      symbol: "US02Y",
      name: "US 2-Year Treasury Yield",
      category: "bonds",
      price: "4.215",
      change: "-0.018",
      changePercent: "-0.43",
      high24h: "4.248",
      low24h: "4.195",
      volume: "$86B",
      marketCap: null,
      peRatio: null,
      dividendYield: "4.21",
      sparkline: [4.28, 4.26, 4.25, 4.24, 4.23, 4.22, 4.215],
      aiSentiment: "Easing Anticipation",
      aiSummary: "Swaps pricing 75 bps of total rate reductions over the upcoming four FOMC meetings.",
      exchange: "Govt Bond Desk",
    },
  ]);

  // 2. Seed 11 GICS Sectors
  await db.insert(sectors).values([
    {
      slug: "technology",
      name: "Information Technology",
      icon: "Cpu",
      description: "Semiconductor architecture, enterprise cloud platforms, software solutions, and AI compute acceleration.",
      marketWeightPercent: "31.85",
      change1D: "1.42",
      change1M: "4.85",
      change1Y: "38.20",
      peRatio: "32.40",
      dividendYield: "0.72",
      topHoldings: [
        { symbol: "NVDA", name: "NVIDIA Corp", weight: "22.4%", price: 138.25, change: 3.12 },
        { symbol: "AAPL", name: "Apple Inc.", weight: "20.8%", price: 232.8, change: 1.05 },
        { symbol: "MSFT", name: "Microsoft Corp", weight: "19.5%", price: 428.5, change: 1.4 },
        { symbol: "AVGO", name: "Broadcom Inc.", weight: "6.8%", price: 176.4, change: 2.9 },
        { symbol: "AMD", name: "Advanced Micro Devices", weight: "3.9%", price: 136.1, change: 2.1 },
      ],
      macroCatalysts: [
        "Sustained Tier-1 cloud enterprise AI compute CapEx",
        "Edge-computing Silicon migration to 3nm and below",
        "SaaS pricing model shift toward consumption tokens",
      ],
      aiOutlook: "Overweight conviction. Accelerated computing infrastructure transition continues to exhibit unmatched pricing power and free cash flow conversion.",
      aiRating: "Overweight",
    },
    {
      slug: "financials",
      name: "Financials",
      icon: "Building2",
      description: "Global money-center banks, asset managers, insurance conglomerates, and capital markets operators.",
      marketWeightPercent: "13.40",
      change1D: "0.58",
      change1M: "3.20",
      change1Y: "26.40",
      peRatio: "16.10",
      dividendYield: "1.85",
      topHoldings: [
        { symbol: "JPM", name: "JPMorgan Chase & Co.", weight: "14.2%", price: 242.6, change: 0.8 },
        { symbol: "BRK.B", name: "Berkshire Hathaway", weight: "12.8%", price: 472.0, change: 0.4 },
        { symbol: "V", name: "Visa Inc.", weight: "8.5%", price: 312.4, change: 0.6 },
        { symbol: "MA", name: "Mastercard Inc.", weight: "7.1%", price: 518.2, change: 0.9 },
        { symbol: "GS", name: "Goldman Sachs Group", weight: "4.8%", price: 588.3, change: 1.2 },
      ],
      macroCatalysts: [
        "Resilient net interest margins across diversified institutions",
        "Rebound in M&A advisory pipelines and IPO sponsor exits",
        "Prudent regulatory capital buffers under Basel III endgame revisions",
      ],
      aiOutlook: "Overweight. Credit losses remain within historic non-recessionary bands while wealth management fee revenue generates countercyclical stability.",
      aiRating: "Overweight",
    },
    {
      slug: "healthcare",
      name: "Healthcare",
      icon: "Activity",
      description: "Pharmaceutical innovation, biotechnology breakthroughs, medical robotics, and managed health insurers.",
      marketWeightPercent: "11.60",
      change1D: "0.22",
      change1M: "1.15",
      change1Y: "11.80",
      peRatio: "21.50",
      dividendYield: "1.65",
      topHoldings: [
        { symbol: "LLY", name: "Eli Lilly and Co.", weight: "13.8%", price: 824.5, change: 1.1 },
        { symbol: "UNH", name: "UnitedHealth Group", weight: "11.9%", price: 594.1, change: -0.3 },
        { symbol: "JNJ", name: "Johnson & Johnson", weight: "8.4%", price: 156.8, change: 0.2 },
        { symbol: "ABBV", name: "AbbVie Inc.", weight: "6.7%", price: 184.2, change: 0.5 },
        { symbol: "MRK", name: "Merck & Co.", weight: "6.1%", price: 104.5, change: 0.1 },
      ],
      macroCatalysts: [
        "Explosive commercial adoption of GLP-1 and incretin-based therapeutics",
        "Aging demographics across G7 nations expanding procedural volumes",
        "AI-enabled molecular discovery compressing target lead times",
      ],
      aiOutlook: "Equal Weight. Valuation bifurcation between mega-cap GLP-1 leaders and mature legacy patent expiration names suggests selective stock-picking.",
      aiRating: "Equal Weight",
    },
    {
      slug: "consumer-discretionary",
      name: "Consumer Discretionary",
      icon: "ShoppingBag",
      description: "E-commerce global marketplaces, electric vehicle manufacturers, premium hospitality, and luxury retail.",
      marketWeightPercent: "10.25",
      change1D: "1.10",
      change1M: "5.40",
      change1Y: "28.90",
      peRatio: "27.80",
      dividendYield: "0.78",
      topHoldings: [
        { symbol: "AMZN", name: "Amazon.com Inc.", weight: "36.2%", price: 202.4, change: 1.75 },
        { symbol: "TSLA", name: "Tesla Inc.", weight: "18.5%", price: 318.9, change: 4.8 },
        { symbol: "HD", name: "The Home Depot", weight: "9.2%", price: 408.0, change: 0.4 },
        { symbol: "MCD", name: "McDonald's Corp", weight: "5.4%", price: 295.1, change: -0.2 },
        { symbol: "NKE", name: "NIKE Inc.", weight: "3.1%", price: 78.4, change: 0.3 },
      ],
      macroCatalysts: [
        "Resilient real wage gains insulating upper-middle income spending",
        "Amazon retail operational efficiency and third-party advertising margin gains",
        "Shift from goods consumption to experiential travel and automated mobility",
      ],
      aiOutlook: "Overweight. Dominant platform ecosystems are capturing larger market shares while smaller retailers absorb discounter margin pressure.",
      aiRating: "Overweight",
    },
    {
      slug: "communication-services",
      name: "Communication Services",
      icon: "Share2",
      description: "Digital search engines, social media networks, streaming entertainment, and broadband telecommunications.",
      marketWeightPercent: "8.90",
      change1D: "1.18",
      change1M: "3.90",
      change1Y: "34.10",
      peRatio: "22.10",
      dividendYield: "0.88",
      topHoldings: [
        { symbol: "META", name: "Meta Platforms Inc.", weight: "27.4%", price: 595.2, change: 1.6 },
        { symbol: "GOOGL", name: "Alphabet Inc. Class A", weight: "24.1%", price: 178.6, change: 1.2 },
        { symbol: "NFLX", name: "Netflix Inc.", weight: "10.5%", price: 890.4, change: 2.1 },
        { symbol: "DIS", name: "Walt Disney Co.", weight: "5.2%", price: 114.2, change: 0.7 },
        { symbol: "TMUS", name: "T-Mobile US Inc.", weight: "4.8%", price: 226.5, change: 0.4 },
      ],
      macroCatalysts: [
        "AI-driven content recommendation algorithms raising user engagement and ad conversion",
        "Streaming profitability inflection via paid-sharing and tiered ad models",
        "Capital return programs via initiating and expanding cash dividends",
      ],
      aiOutlook: "Overweight. Unprecedented digital advertising reach coupled with disciplined headcounts yields superior free cash flow generation.",
      aiRating: "Overweight",
    },
    {
      slug: "industrials",
      name: "Industrials",
      icon: "Cog",
      description: "Aerospace & defense defense contractors, rail transport, electrical grid equipment, and automation machinery.",
      marketWeightPercent: "8.30",
      change1D: "0.45",
      change1M: "2.10",
      change1Y: "21.30",
      peRatio: "23.40",
      dividendYield: "1.42",
      topHoldings: [
        { symbol: "GE", name: "GE Aerospace", weight: "8.1%", price: 182.4, change: 0.9 },
        { symbol: "CAT", name: "Caterpillar Inc.", weight: "7.9%", price: 398.2, change: 0.5 },
        { symbol: "UNP", name: "Union Pacific Corp", weight: "5.8%", price: 236.1, change: 0.2 },
        { symbol: "RTX", name: "RTX Corporation", weight: "5.4%", price: 122.8, change: 0.6 },
        { symbol: "HON", name: "Honeywell International", weight: "4.9%", price: 224.5, change: 0.3 },
      ],
      macroCatalysts: [
        "Government on-shoring incentives (CHIPS Act, Infrastructure programs)",
        "Global commercial aviation fleet replenishment cycles",
        "Power grid transformer shortages supporting pricing backlogs",
      ],
      aiOutlook: "Equal Weight. High historical order books provide defensive visibility, but industrial manufacturing PMIs in Europe pose localized drag.",
      aiRating: "Equal Weight",
    },
    {
      slug: "consumer-staples",
      name: "Consumer Staples",
      icon: "ShieldAlert",
      description: "Essential household staples, packaged goods, beverage distillers, and wholesale club food retailers.",
      marketWeightPercent: "5.80",
      change1D: "-0.15",
      change1M: "-0.40",
      change1Y: "9.20",
      peRatio: "20.20",
      dividendYield: "2.75",
      topHoldings: [
        { symbol: "PG", name: "Procter & Gamble Co.", weight: "15.2%", price: 172.5, change: -0.1 },
        { symbol: "COST", name: "Costco Wholesale Corp", weight: "14.8%", price: 968.0, change: 0.8 },
        { symbol: "KO", name: "The Coca-Cola Co.", weight: "9.8%", price: 65.4, change: 0.1 },
        { symbol: "PEP", name: "PepsiCo Inc.", weight: "8.4%", price: 161.2, change: -0.3 },
        { symbol: "WMT", name: "Walmart Inc.", weight: "12.6%", price: 92.4, change: 0.5 },
      ],
      macroCatalysts: [
        "Stable recurring cash dividend yields for defensive allocators",
        "Unit volume elasticity pushback against repeated price hikes",
        "Private label penetration gains in standard household categories",
      ],
      aiOutlook: "Underweight. Elevated valuation relative to real organic top-line volume growth suggests lower risk-adjusted upside compared to secular growth sectors.",
      aiRating: "Underweight",
    },
    {
      slug: "energy",
      name: "Energy",
      icon: "Flame",
      description: "Integrated oil & gas majors, exploration & production operators, refining, and pipeline midstream infrastructure.",
      marketWeightPercent: "3.60",
      change1D: "-0.45",
      change1M: "-1.80",
      change1Y: "4.80",
      peRatio: "12.80",
      dividendYield: "3.40",
      topHoldings: [
        { symbol: "XOM", name: "Exxon Mobil Corp", weight: "24.5%", price: 120.6, change: -0.5 },
        { symbol: "CVX", name: "Chevron Corp", weight: "16.8%", price: 158.4, change: -0.4 },
        { symbol: "COP", name: "ConocoPhillips", weight: "8.4%", price: 108.2, change: -0.2 },
        { symbol: "EOG", name: "EOG Resources", weight: "5.2%", price: 128.5, change: -0.6 },
        { symbol: "SLB", name: "SLB (Schlumberger)", weight: "4.9%", price: 42.1, change: -0.8 },
      ],
      macroCatalysts: [
        "Disciplined shareholder capital returns (share buybacks and variable dividends)",
        "Permian basin low-breakeven drilling consolidation",
        "Global geopolitical supply risk bottlenecks",
      ],
      aiOutlook: "Equal Weight. Compelling cash generation and low PE multiples provide inflation hedge, though near-term price ceiling is capped by non-OPEC output.",
      aiRating: "Equal Weight",
    },
    {
      slug: "utilities",
      name: "Utilities",
      icon: "Zap",
      description: "Regulated electricity providers, nuclear power operators, clean energy generators, and water utilities.",
      marketWeightPercent: "2.40",
      change1D: "0.65",
      change1M: "2.40",
      change1Y: "24.50",
      peRatio: "19.50",
      dividendYield: "3.20",
      topHoldings: [
        { symbol: "NEE", name: "NextEra Energy Inc.", weight: "28.5%", price: 77.2, change: 0.8 },
        { symbol: "SO", name: "The Southern Company", weight: "12.4%", price: 88.6, change: 0.5 },
        { symbol: "DUK", name: "Duke Energy Corp", weight: "10.8%", price: 114.2, change: 0.4 },
        { symbol: "CEG", name: "Constellation Energy Corp", weight: "9.2%", price: 238.5, change: 1.8 },
        { symbol: "AEP", name: "American Electric Power", weight: "6.5%", price: 98.4, change: 0.3 },
      ],
      macroCatalysts: [
        "Massive power purchase agreements (PPAs) signed directly with AI hyperscalers",
        "Nuclear energy renaissance for baseload 24/7 clean computing",
        "Regulated rate base asset expansion approvals",
      ],
      aiOutlook: "Overweight. Structural re-rating underway as utilities transform from boring bond-proxies into essential AI compute power suppliers.",
      aiRating: "Overweight",
    },
    {
      slug: "real-estate",
      name: "Real Estate (REITs)",
      icon: "Home",
      description: "Data center REITs, cell tower operators, modern logistics warehouses, and residential communities.",
      marketWeightPercent: "2.10",
      change1D: "0.30",
      change1M: "-0.80",
      change1Y: "8.10",
      peRatio: "28.20",
      dividendYield: "3.90",
      topHoldings: [
        { symbol: "PLD", name: "Prologis Inc.", weight: "12.4%", price: 118.6, change: 0.2 },
        { symbol: "AMT", name: "American Tower Corp", weight: "10.8%", price: 198.4, change: 0.4 },
        { symbol: "EQIX", name: "Equinix Inc.", weight: "9.9%", price: 912.0, change: 1.1 },
        { symbol: "PSA", name: "Public Storage", weight: "6.2%", price: 334.5, change: -0.1 },
        { symbol: "DLR", name: "Digital Realty Trust", weight: "6.0%", price: 174.2, change: 0.9 },
      ],
      macroCatalysts: [
        "Unprecedented pre-leasing demand for specialized data center megawatt capacity",
        "Stabilization of commercial mortgage debt refinancing rates",
        "Urban supply constraints keeping industrial logistics vacancy low",
      ],
      aiOutlook: "Equal Weight. Strong secular tailwinds for Digital Realty and Equinix, but traditional office and regional mall headwinds remain a drag.",
      aiRating: "Equal Weight",
    },
    {
      slug: "materials",
      name: "Materials",
      icon: "Boxes",
      description: "Industrial gases, specialty chemicals, lithium producers, steel makers, and packaging materials.",
      marketWeightPercent: "2.00",
      change1D: "0.40",
      change1M: "0.80",
      change1Y: "10.40",
      peRatio: "19.80",
      dividendYield: "2.10",
      topHoldings: [
        { symbol: "LIN", name: "Linde plc", weight: "22.5%", price: 462.8, change: 0.6 },
        { symbol: "SHW", name: "Sherwin-Williams Co.", weight: "9.8%", price: 374.5, change: 0.3 },
        { symbol: "FCX", name: "Freeport-McMoRan Inc.", weight: "7.2%", price: 46.2, change: 1.2 },
        { symbol: "ECL", name: "Ecolab Inc.", weight: "6.8%", price: 248.0, change: 0.4 },
        { symbol: "NEM", name: "Newmont Corp", weight: "5.5%", price: 44.8, change: 0.5 },
      ],
      macroCatalysts: [
        "Copper demand surge for renewable power grid connections",
        "Pricing discipline among industrial gas oligopolies",
        "Gold mining cash flow conversion at record-high bullion spot levels",
      ],
      aiOutlook: "Equal Weight. Copper and gold miners outperform cyclical industrial chemicals facing European margin compression.",
      aiRating: "Equal Weight",
    },
  ]);

  // 3. Seed Plain-English Institutional Earnings Reports
  await db.insert(earningsReports).values([
    {
      symbol: "NVDA",
      companyName: "NVIDIA Corporation",
      sector: "Information Technology",
      reportDate: "Nov 20, 2024",
      fiscalPeriod: "Q3 FY2025",
      epsEstimate: "0.75",
      epsActual: "0.81",
      revenueEstimate: "$33.16B",
      revenueActual: "$35.08B",
      beatStatus: "Beat",
      surprisePercent: "8.00",
      plainEnglishSummary: "NVIDIA beat expectations yet again. Data center revenue jumped 112% to over $30.8 billion in a single quarter as the world's largest cloud giants race to buy every Blackwell and Hopper chip manufactured. Gross margins remained near a staggering 75%.",
      marketReactionReason: "Shares experienced an initial minor consolidation because Wall Street whisper expectations were looking for $36B+, but quickly rallied higher as management confirmed Blackwell architecture demand is 'extraordinary and outstripping supply for several quarters.'",
      guidanceSentiment: "Strong Expansion",
      catalysts: [
        "Blackwell Ultra chips shipping at scale",
        "Enterprise sovereign AI buildouts in Japan, UK, and Middle East",
        "Networking segment (Spectrum-X) crossing $3B quarterly run-rate",
      ],
      keyTakeaways: [
        "Data Center generated $30.8B, up 112% year-over-year",
        "Free cash flow of $16.8 billion returned heavily via buybacks",
        "Gaming and automotive divisions maintained consistent high single-digit growth",
      ],
    },
    {
      symbol: "AAPL",
      companyName: "Apple Inc.",
      sector: "Information Technology",
      reportDate: "Oct 31, 2024",
      fiscalPeriod: "Q4 FY2024",
      epsEstimate: "1.60",
      epsActual: "1.64",
      revenueEstimate: "$94.56B",
      revenueActual: "$94.93B",
      beatStatus: "Beat",
      surprisePercent: "2.50",
      plainEnglishSummary: "Apple posted solid record revenue of nearly $95 billion. The real engine remains Services (App Store, iCloud, Apple Pay, AppleCare), which surged to an all-time record of $24.97B with gross margins above 74%. iPhone 16 sales showed healthy early momentum.",
      marketReactionReason: "Stock traded flat-to-modestly higher. Investors were encouraged by strong active device base growth (surpassing 2.2 billion active devices worldwide) despite watchful eyes on China competitive dynamics.",
      guidanceSentiment: "Bullish",
      catalysts: [
        "Rollout of localized Apple Intelligence features worldwide",
        "High margin Services expansion heading toward $100B annualized",
        "Record install base driving high-repeat replacement cycles",
      ],
      keyTakeaways: [
        "iPhone revenue was $46.22B, up 6% YoY",
        "Services revenue reached $24.97B, up 12% YoY",
        "Generated $26.8B in operating cash flow and returned $29B to shareholders",
      ],
    },
    {
      symbol: "MSFT",
      companyName: "Microsoft Corporation",
      sector: "Information Technology",
      reportDate: "Oct 30, 2024",
      fiscalPeriod: "Q1 FY2025",
      epsEstimate: "3.10",
      epsActual: "3.30",
      revenueEstimate: "$64.51B",
      revenueActual: "$65.59B",
      beatStatus: "Beat",
      surprisePercent: "6.45",
      plainEnglishSummary: "Microsoft delivered a commanding earnings beat powered by Azure Cloud, which grew 33% (with 12 percentage points directly driven by AI model hosting). Enterprise Copilot seats grew over 60% quarter-over-quarter as Fortune 500 companies expanded subscriptions.",
      marketReactionReason: "Market responded positively to management reaffirming that CapEx investments ($20B in the quarter) are driven directly by contracted, paying customer demand rather than speculative speculative buildouts.",
      guidanceSentiment: "Strong Expansion",
      catalysts: [
        "Commercial cloud backlog climbing past $259 billion",
        "Copilot for Microsoft 365 daily active user usage doubling",
        "Security business crossing $25B in annual recurring run rate",
      ],
      keyTakeaways: [
        "Intelligent Cloud revenue was $24.1B, up 20% YoY",
        "Net income grew 11% to $24.7 billion",
        "Free cash flow of $19.3 billion after historic infrastructure deployment",
      ],
    },
    {
      symbol: "AMZN",
      companyName: "Amazon.com Inc.",
      sector: "Consumer Discretionary",
      reportDate: "Oct 31, 2024",
      fiscalPeriod: "Q3 2024",
      epsEstimate: "1.14",
      epsActual: "1.43",
      revenueEstimate: "$157.28B",
      revenueActual: "$158.88B",
      beatStatus: "Beat",
      surprisePercent: "25.44",
      plainEnglishSummary: "Amazon delivered a massive profit beat. Operating income skyrocketed 56% to $17.4 billion (crushing Wall Street targets) as regionalized fulfillment networks slashed delivery costs and high-margin Advertising jumped 19% to $14.3 billion.",
      marketReactionReason: "The stock surged over 6% post-earnings. Analysts cheered the dramatic margin expansion in North American retail operations combined with AWS cloud revenue re-accelerating to 19% growth.",
      guidanceSentiment: "Bullish",
      catalysts: [
        "AWS Bedrock generative AI revenue up triple digits",
        "Same-day delivery speeds lowering cost per unit shipped",
        "Prime Video advertising ramp expanding advertising gross margins",
      ],
      keyTakeaways: [
        "Operating income climbed from $11.2B to $17.4B year-over-year",
        "AWS revenue hit $27.5B, growing 19% YoY",
        "Trailing 12-month free cash flow increased to $47.7 billion",
      ],
    },
    {
      symbol: "TSLA",
      companyName: "Tesla Inc.",
      sector: "Consumer Discretionary",
      reportDate: "Oct 23, 2024",
      fiscalPeriod: "Q3 2024",
      epsEstimate: "0.60",
      epsActual: "0.72",
      revenueEstimate: "$25.37B",
      revenueActual: "$25.18B",
      beatStatus: "Beat",
      surprisePercent: "20.00",
      plainEnglishSummary: "Tesla blew away earnings estimates despite slight top-line revenue slippage. Auto gross margins excluding regulatory credits rebounded to 17.1%, and Cost of Goods Sold per vehicle fell to an all-time company record low of ~$35,100.",
      marketReactionReason: "Stock surged +22% in its best single day in over a decade. Elon Musk guided for 20-30% vehicle delivery growth in 2025 and highlighted rapid progress in Full Self-Driving hardware and Cybercab robotaxi scale.",
      guidanceSentiment: "Bullish",
      catalysts: [
        "Megapack energy storage division gross margin hitting record 30.5%",
        "Unsupervised FSD regulatory trials scheduled in Texas and California",
        "Launch of affordable sub-$30k EV model scheduled for first half of 2025",
      ],
      keyTakeaways: [
        "Automotive gross margin (ex-credits) increased to 17.1%",
        "Operating cash flow reached $6.3B, free cash flow $2.7B",
        "Energy Storage deployments reached 6.9 GWh, up 73% YoY",
      ],
    },
    {
      symbol: "GOOGL",
      companyName: "Alphabet Inc.",
      sector: "Communication Services",
      reportDate: "Oct 29, 2024",
      fiscalPeriod: "Q3 2024",
      epsEstimate: "1.85",
      epsActual: "2.12",
      revenueEstimate: "$86.30B",
      revenueActual: "$88.27B",
      beatStatus: "Beat",
      surprisePercent: "14.59",
      plainEnglishSummary: "Alphabet reported blow-out numbers across all divisions. Google Cloud revenue crossed $11.35 billion with operating margins surging to 11.7% (proving Cloud scale efficiency). Google Search advertising remained rock-solid, up 12% despite AI search competitors.",
      marketReactionReason: "Stock climbed 5%+. The market recognized that AI Overviews are increasing user queries rather than cannibalizing revenue, and YouTube ad revenue rebounded with 12% growth.",
      guidanceSentiment: "Bullish",
      catalysts: [
        "Google Cloud AI enterprise contracts growing 10x YoY",
        "Gemini 2.0 integration across 7 products with 2B+ users each",
        "Disciplined headcount expense yielding operating leverage",
      ],
      keyTakeaways: [
        "Google Cloud operating income was $1.95B vs $266M last year",
        "Total revenue grew 15% year-over-year",
        "Operating margin expanded 400 basis points to 32%",
      ],
    },
    {
      symbol: "JPM",
      companyName: "JPMorgan Chase & Co.",
      sector: "Financials",
      reportDate: "Oct 11, 2024",
      fiscalPeriod: "Q3 2024",
      epsEstimate: "4.01",
      epsActual: "4.37",
      revenueEstimate: "$41.63B",
      revenueActual: "$43.32B",
      beatStatus: "Beat",
      surprisePercent: "8.98",
      plainEnglishSummary: "America's largest bank posted another fortress quarter. Investment banking fees jumped 31% as debt underwriting and equity issuance resumed, while net interest income remained high at $23.5 billion despite interest rate cuts.",
      marketReactionReason: "Stock traded up to new all-time highs. CEO Jamie Dimon raised full-year net interest income guidance to $92.5 billion and demonstrated industry-leading return on tangible common equity (ROTCE) of 19%.",
      guidanceSentiment: "Cautious",
      catalysts: [
        "Resurgence in corporate advisory and private equity syndication",
        "Credit card charge-offs stabilizing at pre-pandemic normal bands",
        "Market share capture from regional deposit flight",
      ],
      keyTakeaways: [
        "Net income of $12.9 billion with 19% ROTCE",
        "Investment banking fees up 31% YoY to $2.27 billion",
        "CET1 regulatory capital ratio stands at a fortress 15.3%",
      ],
    },
    {
      symbol: "LLY",
      companyName: "Eli Lilly and Co.",
      sector: "Healthcare",
      reportDate: "Oct 30, 2024",
      fiscalPeriod: "Q3 2024",
      epsEstimate: "1.47",
      epsActual: "1.18",
      revenueEstimate: "$12.11B",
      revenueActual: "$11.44B",
      beatStatus: "Miss",
      surprisePercent: "-19.70",
      plainEnglishSummary: "Eli Lilly missed short-term Wall Street estimates as US wholesale inventory destocking clipped reported sales of Mounjaro and Zepbound. However, underlying end-market patient prescriptions continued to grow at historic double-digit weekly rates.",
      marketReactionReason: "Shares pulled back ~6% before finding strong institutional buyer support. Management highlighted that manufacturing capacity has doubled and self-pay single-dose vials are expanding total addressable patient access.",
      guidanceSentiment: "Bullish",
      catalysts: [
        "$9B in new manufacturing facilities coming online across US and Europe",
        "Pipeline readout for oral GLP-1 candidate (Orforglipron)",
        "Label expansion for sleep apnea and cardiovascular risk reduction",
      ],
      keyTakeaways: [
        "Zepbound sales reached $1.26 billion in Q3 alone",
        "Mounjaro sales surged to $3.11 billion, up 121% YoY",
        "Total company revenue rose 20% despite wholesale destocking",
      ],
    },
  ]);

  // 4. Seed Live Market Alerts
  await db.insert(marketAlerts).values([
    {
      title: "FOMC Policy Trajectory Update",
      symbol: "SPX",
      severity: "urgent",
      category: "Central Bank",
      message: "Federal Reserve chair signals balanced 25bps recalibration trajectory with dot plot pointing toward 3.4% neutral terminal rate.",
      timestampStr: "12 mins ago",
      read: false,
    },
    {
      title: "Mega-Cap AI Infrastructure CapEx Target",
      symbol: "NVDA",
      severity: "high",
      category: "Earnings",
      message: "Combined Tier-1 hyperscaler forward capital expenditure raised to $210B annualized; Blackwell node allocation at 100% capacity.",
      timestampStr: "45 mins ago",
      read: false,
    },
    {
      title: "OPEC+ Supply Restraint Rollover",
      symbol: "BRENT",
      severity: "info",
      category: "Volatility",
      message: "Vienna delegates agree to prolong 2.2M bpd voluntary crude trims through Q2 2025 to balance non-OPEC deepwater flows.",
      timestampStr: "2 hours ago",
      read: false,
    },
    {
      title: "Bitcoin Institutional Custody Inflows",
      symbol: "BTC",
      severity: "high",
      category: "Breakout",
      message: "Global exchange-traded products register 5th consecutive week of net inflows with CME open interest setting new historical peak.",
      timestampStr: "3 hours ago",
      read: true,
    },
  ]);

  // 5. Seed User Watchlist
  await db.insert(userWatchlist).values([
    {
      userId: "guest_institutional_user",
      symbol: "NVDA",
      name: "NVIDIA Corp",
      priceAtAdd: "135.20",
      targetPrice: "165.00",
      notes: "Blackwell production ramp validation; key catalyst is enterprise data center backlog expansion.",
      alertCondition: "above",
    },
    {
      userId: "guest_institutional_user",
      symbol: "BTC",
      name: "Bitcoin",
      priceAtAdd: "91400.00",
      targetPrice: "105000.00",
      notes: "Macro liquidity tailwind; monitoring weekly institutional spot ETF absorption pace.",
      alertCondition: "above",
    },
    {
      userId: "guest_institutional_user",
      symbol: "SPX",
      name: "S&P 500 Index",
      priceAtAdd: "5860.00",
      targetPrice: "6150.00",
      notes: "Broad market index benchmark; watching Q4 corporate earnings revision breadth.",
      alertCondition: "above",
    },
    {
      userId: "guest_institutional_user",
      symbol: "GOLD",
      name: "Spot Gold",
      priceAtAdd: "2640.00",
      targetPrice: "2800.00",
      notes: "Hedge against sovereign debt expansion and central bank reserve diversification.",
      alertCondition: "above",
    },
  ]);

  // 6. Seed Sample AI Support Tickets (Demonstrating 24/7 Automated Support System)
  await db.insert(supportTickets).values([
    {
      name: "Marcus Vance",
      email: "m.vance@citadel-alphacap.com",
      tier: "Institutional",
      subject: "WebSocket Sub-second Feed Latency Verification",
      category: "Terminal & Data",
      message: "Requesting server-side timestamp verification for FIX protocol quotes on SPX and NDX constituents compared to Chicago CME direct feed.",
      status: "AI Resolved",
      priority: "Urgent",
      aiResponse: "SG16 Sentinel AI System Automated Resolution: Your institutional sub-second feed operates via AWS eu-west-1 & us-east-1 direct cross-connects with measured 99th-percentile jitter under 1.84ms. The timestamp telemetry payload is embedded in UTC nanoseconds (RFC-3339) in every WebSocket broadcast. Detailed latency audit report #SG16-LAT-8941 has been generated and appended to your portal dashboard.",
      aiConfidence: "99.40",
    },
    {
      name: "Elena Rostova",
      email: "e.rostova@geneva-sovereign.ch",
      tier: "Sovereign",
      subject: "Custom Risk Parity Beta Model Calculation for Global Equities",
      category: "Portfolio Model",
      message: "How does SG16 Finance calculate the rolling 90-day covariance matrix between our GICS tech constituents and 10-Year US Treasuries?",
      status: "AI Resolved",
      priority: "High",
      aiResponse: "SG16 Sentinel AI Automated Quantitative Breakdown: The rolling 90-day covariance matrix uses an exponential decay factor of lambda = 0.94 (RiskMetrics convention) normalized against daily continuous compounded returns. Your Sovereign tier API endpoint `/api/portfolio/covariance` now exports this matrix in JSON, Parquet, and CSV formats with automated correlation breakdown.",
      aiConfidence: "98.90",
    },
    {
      name: "David Chen",
      email: "david@lumina-investments.sg",
      tier: "VIP Pro",
      subject: "Automated Earnings Surprise Webhook Notification",
      category: "API Access",
      message: "Can we configure real-time webhook triggers to receive plain-English earnings breakdowns within 60 seconds of SEC 8-K filings?",
      status: "AI Resolved",
      priority: "High",
      aiResponse: "SG16 Sentinel AI System Automated Resolution: Confirmed. Webhook triggers for SEC 8-K / 10-Q filings are processed by our low-latency NLP parsing engine within 18 to 42 seconds of EDGAR release. You can activate this directly in your SG16 Account Settings -> Webhooks tab with your target symbol watchlist.",
      aiConfidence: "99.10",
    },
  ]);
}
